### ISSUE TITLE
Planning to integrate with diffusers?

### ISSUE THREAD

**Issue by AmanKishore** [dbolya/tomesd#1]
Question in title

**Comment by dbolya** [comment]
I haven't had time to look into it, but if it's not too difficult I'll do it.

**Comment by AmanKishore** [comment]
Awesome thank you, let me know if I can help!

**Comment by kelisiya** [comment]
+1

**Comment by dbolya** [comment]
Diffusers support has been added (thanks to @JunnYu and @ExponentialML)!
