### ISSUE TITLE
unable to load LoRA

### ISSUE THREAD

**Issue by Shreddertheman** [dbolya/tomesd#10]
I seem to be unable to use LoRA while using this, does anyone have any idea why this happens, I get an error telling me to enable no half and turn on " Upcast cross attention layer to float32 " but this causes black images

**Comment by dbolya** [comment]
I believe LoRAs should work if you use the [PR here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9256) for integration with the webui. Feel free to reopen if you're still having issues.
