### ISSUE TITLE
Settings Guide

### ISSUE THREAD

**Issue by YKefasu** [dbolya/tomesd#11]
can you please make a wiki or explanation for each parameter in the settings. thankyou
I'm still new to understanding this setting😅
![image](https://user-images.githubusercontent.com/129555908/229252138-54325e07-999f-4826-baa8-c1cfc8286a35.png)

**Comment by dbolya** [comment]
For any future onlookers, there's a docstring at the top of the "apply_patch" function that explains it (in patch.py).

**Comment by AlbieRWang** [comment]
could u tell me how to use it on webui,thanks

**Comment by dbolya** [comment]
> could u tell me how to use it on webui,thanks

Use this PR: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9256  
(Google how to checkout a PR if you don't know).
