### ISSUE TITLE
AttributeError: 'ToMeBlock' object has no attribute 'use_ada_layer_norm_zero'

### ISSUE THREAD

**Issue by ZhenYangCS** [dbolya/tomesd#20]
Hi, When I run the code of demo:
<img width="925" alt="截屏2023-04-11 16 38 44" src="https://user-images.githubusercontent.com/126039144/231104646-7d4edd7f-fa7a-4f2b-8694-234dae3f2b76.png">

could you please tell me why it give me the error of: 
<img width="662" alt="截屏2023-04-11 16 37 26" src="https://user-images.githubusercontent.com/126039144/231104763-646bba02-c2ac-4b86-8cdf-b1c3289af257.png">

My diffusers version is 0.11.1, when I set 
<img width="340" alt="截屏2023-04-11 19 58 28" src="https://user-images.githubusercontent.com/126039144/231155974-6551bd3a-2ff4-40c2-bb61-134189a856fd.png">
it works. It seems use_ada_layer_norm_zero and use_ada_layer_norm isn't in the diffusors.

**Comment by dbolya** [comment]
Thanks for bringing this to my attention. Seems those attributes are there in the latest version of diffusers (0.14), but I guess not in 0.11.

I'll add a work around in tomesd 0.1.3. No reason not to support older versions if it's that simple.
