### ISSUE TITLE
mac :Failed to apply ToMe patch, continuing as normal module 'tomesd' has no attribute 'apply_patch'

### ISSUE THREAD

**Issue by oldwhite83** [dbolya/tomesd#22]
setup
![image](https://user-images.githubusercontent.com/12129950/233934849-6c2bf86b-4fd6-440d-9681-49d140ecc88c.png)

but start ./webui.sh

![image](https://user-images.githubusercontent.com/12129950/233935224-4f0f2bc9-ff5c-4222-99cc-1e60d00af819.png)

**Comment by dbolya** [comment]
Hi, this looks like you didn't install tomesd to the correct python environment, as "apply_patch" has been in the tomesd package from day 0.  
Regardless, this is not the right place for issues with using tomesd for external applications, so closing the issue. If you need help, you should probably ask the thread with the PR / extension you're using.
