### ISSUE TITLE
Question: how to save optimized model?

### ISSUE THREAD

**Issue by recoilme** [dbolya/tomesd#26]
i try to load to pipe, apply patch and save result to diffusers format and convert to ckpt, but get same file size.. 2.13Gb
Is it possible to store/save optimized model?

output during conversion:
```
Reshaping encoder.mid.attn_1.q.weight for SD format
Reshaping encoder.mid.attn_1.k.weight for SD format
Reshaping encoder.mid.attn_1.v.weight for SD format
Reshaping encoder.mid.attn_1.proj_out.weight for SD format
Reshaping decoder.mid.attn_1.q.weight for SD format
Reshaping decoder.mid.attn_1.k.weight for SD format
Reshaping decoder.mid.attn_1.v.weight for SD format
Reshaping decoder.mid.attn_1.proj_out.weight for SD format
```

**Comment by dbolya** [comment]
ToMe has no parameters doesn't affect the weights of the model at all, so no. The tomesd code needs to be run for tokens to be merged.
