### ISSUE TITLE
Publish on pip

### ISSUE THREAD

**Issue by space-nuko** [dbolya/tomesd#3]
Since this requires manual installation, would be much more convenient to have it on pip. That way it can be installed from the webui extension without any extra python muckery

**Comment by dbolya** [comment]
Fair enough, I'll make a package for it when I have time.

**Comment by pushstartvr** [comment]
oh please brother, im scared to break things

**Comment by mkshing** [comment]
@dbolya Hi, thanks for your awesome work. 
I actually enabled to do pip install by just forking (from the latest commit [4f936c257e10848e0399fc6d0484a1761812092a](https://github.com/dbolya/tomesd/commit/4f936c257e10848e0399fc6d0484a1761812092a))
- https://github.com/mkshing/tomesd
- https://pypi.org/project/tomesd/
```
$ pip install tomesd
```

If you plan to update your code, I think I should send a PR and hand over the maintainer. Please feel free to message me.

**Comment by dbolya** [comment]
Hi @mkshing, thanks for doing this. I do plan on updating the code continuously, so I think it would be best if I could maintain it.  
The requirements (`torch>=1.12.1`) are also not set up properly atm.

**Comment by mkshing** [comment]
@dbolya Hi, I created a PR. https://github.com/dbolya/tomesd/pull/14 Please review it. Thanks!

**Comment by mkshing** [comment]
@dbolya Thank you for your quick work. I successfully installed v0.1.1. I think you can close this issue.

**Comment by dbolya** [comment]
Thanks for all the help @mkshing! Closing the issue now.
