### ISSUE TITLE
It is installed, but the item does not appear

### ISSUE THREAD

**Issue by taka0070** [dbolya/tomesd#36]
The install itself went well, but for some reason the items to check do not appear on the main screen. There is no item in settings.
![WS000002](https://user-images.githubusercontent.com/129574158/236611601-1299c3f9-9a21-4cb5-ad18-f0b8c5b62c85.JPG)

**Comment by papuSpartan** [comment]
> The install itself went well, but for some reason the items to check do not appear on the main screen. There is no item in settings.

This repo isn't an sdwui extension, it's only a module. There are extensions which use this module to enable tomesd though.

**Comment by dbolya** [comment]
Yes, please google ToMe for SD web ui extensions--there are plenty out there (including a PR request in the automatic repo). Closing the issue.
