### ISSUE TITLE
Update release past 0.1.2 to incorporate subsequent merges for new pip installs?

### ISSUE THREAD

**Issue by jrittvo** [dbolya/tomesd#38]
Automatic1111 has just merged the PR that adds tomesd into their dev branch.  They are using tomesd>=0.1.2 in their requirements_versions.txt.  Could a new tomesd version be released to incorporate commits 2e37b87 and 8fca570 so that a pip install is up to date with this repo?

**Comment by dbolya** [comment]
Thanks for the reminder, v0.1.3 is now released.
