### ISSUE TITLE
Difficulty in calculating FID

### ISSUE THREAD

**Issue by ZTzxj** [dbolya/tomesd#56]
Hello, I'm having trouble trying to solve FID with the generated dataset, I get an error running the pytorch_fid file, the error is reported as follows:File "/home/share449/.conda/envs/fastersd/lib/python3.9/site-packages/torch/ utils/data/_utils/collate.py", line 162, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 375, 500] at entry 0 and [3, 400, 500] at entry 2
It seems to be because the images in the ImageNet val dataset are not of the same size, so I would like to ask you how you deal with this problem, sorry to bother you, very much looking forward to your answer, thank you!

**Comment by dbolya** [comment]
Thanks for pointing this out. It looks like I pre-processed the ImageNet images by scaling the shorter side to 300 and taking a 300x300 center crop (though looking at the images in my fid folder, it seems to actually be 299x299---off by one error?).

**Comment by ZTzxj** [comment]
Thank you very much for your answer, with your help I solved the problem after resizing the image before  before dataloader
