### ISSUE TITLE
no speed up

### ISSUE THREAD

**Issue by marson666** [dbolya/tomesd#6]
hi bro, thanks for your great work!

I just test the tome with xformers==0.0.16 using 3090, the inference speed is the same with only use xformers, i guess maybe something i configured wrong. Have you tested other types of gpus other than 4090 in your paper described?

**Comment by dbolya** [comment]
Hi, thanks for the interest. What image size are you using? With xformers I didn't see a difference until large images (maybe because the merge operation isn't as optimized as xformers).

If you disable xformers do you see a speed-up?

**Comment by marson666** [comment]
Oh, maybe i test 512x512 image size, tome not take effect obviously

i test 1024x1024 images, tome works!
xformers + tome = 6.9s/image
xformers = 9.1s/image


512x1024 images
xformers + tome = 3.3s/image
xformers = 3.8s/image
